version: "2.4"
services:
  ember:
    build:
      context: ember
    volumes:
      - .:/ember
      - .bash_history:/root/.bash_history
      - node_modules:/ember/node_modules
    tmpfs:
      - /ember/tmp
    ports:
      - "4200:4200"
      - "7020:7020"
      - "7357:7357"

  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    # platform: linux/arm64/v8  

  rails:
    build:
      context: rails
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    # platform: linux/arm64/v8  

volumes:
  node_modules:
